name: media_utils
description: An help library to media format.
version: 1.0.1
author: Jonny Borges <jonataborges01@gmail.com>
homepage: https://github.com/JonnyBorges/media_utils

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
